### ISSUE TITLE
Why use different BLUR_KERNEL in post-processing?

### ISSUE THREAD

**Issue by rhifbjbfdg** [ilovepose/DarkPose#22]
For the input size of 128x96, BLUR_KERNEL is 3. However, BLUR_KERNEL is 11 for the input size of 256x192. Can you explain the reason? Thanks.

**Comment by djangogo** [comment]
Because the input size is increased.
In fact, for the large input size,  
if you the kernel size to 3 or 7 or 9 or 11,  you can obtain almost the same AP results (although the AP is increased slightly).
For small input size, the kernel size has a significant impact on the performance, you should set it to a small value.
